---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress-casaebottega
  namespace: wordpress-guests
spec:
  interval: 15m
  chart:
    spec:
      chart: wordpress
      version: 13.6.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    resources:
      limits:
        cpu: 50m
      requests:
        cpu: 50m
    workload:
      main:
        replicas: 2
    php-config:
      PHP_MEMORY_LIMIT: "2048M"
      PHP_POST_MAX_SIZE: "2048M"
      PHP_UPLOAD_MAX_FILESIZE: "2048M"
    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_KEY}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            cleanupTempPvc: true
            cleanupCachePvc: true
            dest:
             enabled: false
            src:
              pruneIntervalDays: 7
              trigger:
                schedule: "21 15 * * *"
              retain:
                hourly: 5
                daily: 5
                weekly: 1
                monthly: 1
                yearly: 1
              enabled: true
    mariadb:
      workload:
        main:
          replicas: 2
    ingress:
      wordpress:
        enabled: true
        primary: true
        ingressClassName: external
        hosts:
          - host: www.ristocasaebottega.it
            paths: 
              - path: /
          - host: wordpress-casaebottega.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
              - www.ristocasaebottega.it
              - wordpress-casaebottega.cloud.local
        integrations:
          traefik:
            enabled: false
