apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/cnpg: fc940fff4269c53072f7039f0811133e9b83400670af014010bf50d3f13740f4
    checksum/configmaps: c461e6076c76639bcd02ef1c58117d0596256865a2c661a92ac419f436d5708e
    checksum/mariadb: 6e8d2416a35654479c293e4cb643a9537e259ea91d8a99f04dd6340d7c61e5bc
    checksum/mongodb: 09c85576cb45b1eecd1467732b11ea8fa3363b0105c465f02a6ad64991521d52
    checksum/persistence: 31306d3ff9f53ad27a5f3598768b7ab55274761c5fd9a8653b9958872c419c84
    checksum/redis: 013343a028cbb3f7e08f4ba7522702dd98e52632c688641074b0b1db3df29894
    checksum/secrets: f82283232691d05230e084cac8ef1f35f3293e5a17ab331cf5171a94a030d623
    checksum/services: 27de331cffc9103581be5e1ab4da8b6ba7e865fe6b205fbe15f495de734f5609
    checksum/solr: 29c14feeaddbf7762052db593898d274941f539cee681ddc613957587686f347
  creationTimestamp: "2026-06-18T10:00:41Z"
  generateName: wordpress-casaebottega-85c79d4b85-
  generation: 1
  labels:
    app: wordpress-13.6.9
    app.kubernetes.io/instance: wordpress-casaebottega
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: latest
    helm-revision: "235"
    helm.sh/chart: wordpress-13.6.9
    pod-template-hash: 85c79d4b85
    pod.lifecycle: permanent
    pod.name: main
    release: wordpress-casaebottega
    truecharts.org/pvc: config
  name: wordpress-casaebottega-85c79d4b85-d2jbf
  namespace: wordpress-guests
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: wordpress-casaebottega-85c79d4b85
    uid: 0f9f35b3-2c06-4f72-805b-38945efea407
  resourceVersion: "318408107"
  uid: dd624ac2-0449-4578-b96d-1175a4fd21a3
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: truecharts.org/pvc
            operator: In
            values:
            - config
        topologyKey: kubernetes.io/hostname
  automountServiceAccountToken: false
  containers:
  - env:
    - name: TZ
      value: UTC
    - name: UMASK
      value: "0022"
    - name: UMASK_SET
      value: "0022"
    - name: NVIDIA_VISIBLE_DEVICES
      value: void
    - name: PUID
      value: "568"
    - name: USER_ID
      value: "568"
    - name: UID
      value: "568"
    - name: PGID
      value: "568"
    - name: GROUP_ID
      value: "568"
    - name: GID
      value: "568"
    envFrom:
    - configMapRef:
        name: wordpress-casaebottega-env-config
    - secretRef:
        name: wordpress-casaebottega-env-secret
    image: docker.io/bitnamisecure/wordpress:latest@sha256:4afe2398a1478c69290b3b45922443fab2b71dc58fc43ce263e266c523227b24
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 12
      periodSeconds: 15
      successThreshold: 1
      tcpSocket:
        port: 10591
      timeoutSeconds: 5
    name: wordpress-casaebottega
    ports:
    - containerPort: 10591
      name: main
      protocol: TCP
    readinessProbe:
      failureThreshold: 4
      initialDelaySeconds: 10
      periodSeconds: 12
      successThreshold: 2
      tcpSocket:
        port: 10591
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 1500m
        memory: 2400Mi
      requests:
        cpu: 75m
        memory: 200Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 568
      seccompProfile:
        type: RuntimeDefault
    startupProbe:
      failureThreshold: 60
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 10591
      timeoutSeconds: 3
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/wordpress
      name: config
    - mountPath: /dev/shm
      name: devshm
    - mountPath: /shared
      name: shared
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/logs
      name: varlogs
    - mountPath: /var/run
      name: varrun
  dnsConfig:
    options:
    - name: ndots
      value: "1"
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  hostUsers: true
  initContainers:
  - command:
    - /bin/sh
    - -c
    - |-
      /bin/bash <<'EOF'
      echo "Executing DB waits..."
      until
        mysqladmin -uroot -h"${MARIADB_HOST}" -p"${MARIADB_ROOT_PASSWORD}" ping \
        && mysqladmin -uroot -h"${MARIADB_HOST}" -p"${MARIADB_ROOT_PASSWORD}" status;
        do sleep 2;
      done
      EOF
    env:
    - name: TZ
      value: UTC
    - name: UMASK
      value: "0022"
    - name: UMASK_SET
      value: "0022"
    - name: NVIDIA_VISIBLE_DEVICES
      value: void
    - name: S6_READ_ONLY_ROOT
      value: "1"
    - name: MARIADB_HOST
      valueFrom:
        secretKeyRef:
          key: plainhost
          name: wordpress-casaebottega-mariadbcreds
    - name: MARIADB_ROOT_PASSWORD
      value: PLACEHOLDERROOTPASSWORD
    image: oci.trueforge.org/containerforge/mariadb-client:12.2.2@sha256:a731429e1a17c24609eea50b0705ff5ad2e74fde98545d465f41bf2175a9c2e4
    imagePullPolicy: IfNotPresent
    name: wordpress-casaebottega-system-mariadb-wait
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 568
      runAsNonRoot: true
      runAsUser: 568
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: devshm
    - mountPath: /shared
      name: shared
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/logs
      name: varlogs
    - mountPath: /var/run
      name: varrun
  nodeSelector:
    kubernetes.io/arch: amd64
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups:
    - 568
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/instance: wordpress-casaebottega
    maxSkew: 1
    nodeAffinityPolicy: Ignore
    nodeTaintsPolicy: Ignore
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 2400Mi
    name: devshm
  - emptyDir: {}
    name: shared
  - emptyDir:
      medium: Memory
      sizeLimit: 2400Mi
    name: tmp
  - emptyDir:
      medium: Memory
      sizeLimit: 2400Mi
    name: varlogs
  - emptyDir:
      medium: Memory
      sizeLimit: 2400Mi
    name: varrun
  - name: config
    persistentVolumeClaim:
      claimName: wordpress-casaebottega-config
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-18T10:00:41Z"
    message: '0/3 nodes are available: 1 node(s) didn''t match pod topology spread
      constraints, 2 node(s) didn''t match pod affinity rules. no new claims to deallocate,
      preemption: 0/3 nodes are available: 1 No preemption victims found for incoming
      pod, 2 Preemption is not helpful for scheduling.'
    observedGeneration: 1
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
