---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: genea
  namespace: genea
spec:
  interval: 15m
  chart:
    spec:
      chart: genea
      version: 7.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      genea:
        enabled: true
        primary: true
        ingressClassName: external
        hosts:
          - host: "genea.${DOMAIN_0}"
            paths:
              - path: /
          - host: genea.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
              - "genea.${DOMAIN_0}"
              - genea.cloud.local