apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5ux2OBLqLt17IEq9d4ltcLF1W9kYZ9NcsY2XQV+o6YOvy8b2/Al00ps/eNSA7VAGHHTfk2isvTygNx52q5QLS8q/rSHCjmrj4Vsjbe2qPiYc0zzDlzUTcYHDqRtL/V9RKxRENMF/ejOOXiR+60eFInSqnt5lyPMqEVviKYmIQGBfkr4arcnr6S2SkhiUPObt212wwxK/mRBn29qWf9uqBh0VIlp2SlY2KdC8I9CJvawoDNV4T61jywM2KzvrKrBLnrWIomnh2Wo9P3OwyaEV4MJcv/zJ/Hsgi6xypToB3XqcJTAnEj+N9rUgKvGCE2RseRSIFBD2yk0gvt51TyIdb7nercRppdU8Ak6rqFGjYGtLJ0PFP298Ke148kHolGLW,iv:tVWiTtBpy4RuJ8S9DFEdlnMNzYtSVFI0Z4KcsEVae9k=,tag:xdgEIbpaVIDbsjLhEs6utQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:IQEwuN9U+NFcP1fbndBz1Vo3O09dM3XDFf/IEArGIjlZR2Jqh32zJQ8FAhi155+HXNyTi9bsT5NtU49bjSXW4M7WkWmOtIFsPSwjQ6pEwMBbS30I7BU0eM26l1+2KxuQ8MChdwlto/d43yDUtMALhPd1aj4xKH16D/ZmM23NmxXMRBw2ZhCaejHHJ6KNMQ6OM6c+1qSt22007sUau3Q1OQExPRlBOQTIuiiXF339/yEVuE2Jw6J+xplmio4aXzKQKTcX08Zlfg3GFIdJeA==,iv:dlGbeZXe67j1BZ6YXZSy7bQOefWL5A8QFn9922IY+To=,tag:2u9iVK2tYDYH4Pe92UYVNQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:jNs2gk8FPFxkutPqs9Q3ndZ+4GAUBju/qE6Iw75eIhO2yA8W+2IuTE23hA1gZpSyAsVq5ij0Yb2XL/BGAUedM4BB/CtTgEJK+CKma4EqddLcsC9yP7fBUaJdBWG45dNKRXRojMi8kCXl52nEug8m62AkPsANGj1ekQ/n4xxozak4r9JnpB+K0yj6Biq4PTVxAldqMUr3aoRjnczC4AbGuFQ1ulvzVMXmjfy3,iv:ukY3+eOhoW/YAezSS2J6Cwa2/2Evt2B1HETPd2gyBvI=,tag:ABsIIzrgqXuaynIQ13cxdQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWnluUFhSTjlVUDZVR3RU
            clFqVmx1NWxHbDY0K2k4VVg2YXVGSTl3WVM4CkUyZzBLY2tHS2U0TmkydDRaMXRE
            ZlFteG1BVzhDZ2d0OTB5dlVrRVRUMWsKLS0tIFpPZWNxTUcrQklvd1F4RmRUa0Rl
            cCswWVNldXpkOGxaTHAxZkNnZk5OckEKXx8o5wrvvmrTUqBijQqcv+2kuc0B3fFm
            JvXAB1aYXZBkVI1ILnjN+LNrPwQjcP2rdHaCpcOy6fTINbehV7AmKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T14:14:01Z"
    mac: ENC[AES256_GCM,data:nmhPGhpirmhnGO1jnstDQDksJLseR0KxY13yADFw7cVpt47VgJm+1lBXGXXiKO7ybVNOlJzKc+nCUdwMGXgk322WWmBgM0z0V30pKLw8XjMJmYhEO8Q2aaT9IaHhPAZTBAmJzm/oiXFoEizDiW0Zq3yH+AaxoyFWdQClAVLepaI=,iv:JrTOj6MMxQYHLjJjw+8EZ1klNY+xtOU9RloAlFEUEck=,tag:kDWyKXp+wElSU/0Y4RfRPw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
