apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0fh8iSAidGum0DHHIlfGcWTDNovkAHJpUIaB/OVqX86LW64lIEtyipjE5gtk/yArQD5cizkJnFTucALXXUL0Sfb7mxOwAC1lnK8aKFS7H1Uon7e9IFbO7VfIkngGFmTKPD+cK6Ctn4HRpD+dzG84z1tyKQ0wx6+SJeViY85PIJ/s5qnn7VYbx5dkDyU0rZC1jYTd4k8nHW3tGjKVDm+ETkgAIjKBZ9oEKk918W2rhXkaAQP9gGWOQH5kcipik0SG2/ZF28zMAogL7qvIZroboA5OJmpZ4QQQtOuVXnbkNHqoixRrMM7cUhnoxN8rmA8GOaES3RCG4weHvcHr/NbKFIY/aItkrmaI5sFXMI/BqThfUvl8V2HqX4TUolmGHD6k,iv:U0nENN+kWyemKUg3d7hE2D4P1xxrTnDcYbCpzRUM8GA=,tag:UJ13kHPAcJ4aJ00cH59a5Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:0yNgZWef9AjzQXQZVj46vY2fmuUEuTusQiyN9K1w6TmOuSWE6A+t2f5NDK98RldS+mjVBQYuC5s3zES9M3OFrnRi/D0RDcDkCZwbTW1bgCbhGvWboMNWIuj7HrOAgqbFm1XyhHLH2d6trgzBP4R2uAfc5sRAGiE00xQ5L+f31ULGWmsoNjUygFPy6UiA//5jQBsHFLpznc4IlaFpDiotd+GUOzi7njpUTwRIp8rWZjyMwmiSWD75yiZc8ui+EEclkDMgKYYZGyj86n1shg==,iv:jnvBBnnxrZSE6oDIRkZhlVATeHzMxwXd+/H8MnSdKoU=,tag:xyL7FAN0lYq6z9uRr+L6Qw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BDCcIm4pMl9IZWS6w5RxWifzRCp37XwIg6FA9d2oZc4RX3OXs9HAN0AYmbhcv5uPInLN9+hAtAMh9O4Fo2KlZRHsP7yo6rtSvDfsKyzZeMAJ9wcDCnF8iEo4vI+7Cco1NbSUDRI78/TyGcxiUbe8cpkZ/AKR3Ama7Nz6bPzH6sciFK71rAiycAAjSTE9Cx5xh94iiK2HW1U8b3aecdJSPBSGhwBKidLJVdaL,iv:5d6x3/J7KBSCDC9E/d4MUywlnN4551SOVuc+6PzqMjc=,tag:foTqI5CUCvLZrmgolFIumQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdm01U2p5YVdtZUhtRjRQ
            U1pES3NtSk5VdW9kVmlsT1FEY2R4V3Bma3pVClEwQ1lmSnBDYlV6bitTUXl2V1BD
            b3R0MjU5VG0vdDFVem5xWFM0N1ZhZzQKLS0tIGNNcmp4Y2xXVlhsWFdqTjdLNDAw
            cXE0UHZNUXBGVU9tSHRPUllHYnJ4TjAKddheaRdHoL5NknCyiZKUF+Vpu8W7Lnap
            FhIp5gp/hdtv0Ups6a9Xj28xl6SGgDIfnMGG5ajH5pUtkgRCIroe8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-17T16:11:43Z"
    mac: ENC[AES256_GCM,data:QSKFMlO04UldiaM8guh2DMNfdiTR9y9wi1cfaaaYhGbsZd/Q5m5uTv95dEaULOxYAQp7clLY8Eb23BblUZqB3jks/rFTHC7OeXYd/e0A9obE9inaq27y5r8Tq3OzKV1FGFMwNGTWoAfI3vxBdFlTAy65Fx5eB8AcMJlg93b+gxo=,iv:999eAKN//vaGIhZwD4KDNGXzVrvw03Tsd7WSPVIEtmw=,tag:bmHQAEKpWTh4phOXDwIhLA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
