apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FVuLe0uORNBdfNVpNihJC6XSjhdQ9CR7okOmzlKbi5RkupZ1+1B1v5i9bCzY8VPdN8k20DCmVq0dMc3pcIXFrhm83rQi6ahOQV5vM9Wy2ygJeHRKuIWce5qlPc8TBtkDsjXd7iF7tc3Q8rFK31O//oc36BgauRrCA4IZxCvs121PXQevtZjJAkCh4rkHlt4/t+hWhpsWdtHvMndVJeS5qUKlvRauPJVcU1YHUJo+9lILUrjrEvLGQqoYUSkqAGRJ9Aez/NPtrkNMqx3EqGTv4xTxSh9CpQynQttTE5upWGQXoejoP/RO/YAHYeXiVtdq+E+n7ZBveJF0r0fpFwliDnsRhLIZu5u42/KtevdW5sWvNEqznIm2HfbEvUvLQOL0hppv5wEF5ov+OduZZMld6OUp5wBmaK6T08DpOykVzzsjFLCiJAteyS1jVHJ2LVerSzkZ13lFtvtnY/Qxyi+FGFFZIB3MVW6xK/rCvPgK/blRwcK2JclTkLDNpSmbI2wPXv0FCJhHOtYCJJB78ZbVOJ6/wgdngfQbrYNzvoLg0fy7immeOapy0+vgs95fx1QT5C9j0eriInObTjrIKztssfuTXBa27u8baCySPzG24DjMdjwkLTOGB//WaAKZRQSighxwhbv7MvAMuemvJ9kTAlWYl95U17AFEth6Sa6HAa8CAzwC1VQIW7dD729kuM5RFjd1Fyfb1Iyty08IBoJxrveFcPtF81puBO7YT0gdHOqU5HnyqODaVx8YNbfnzy0XXCOiGteEpas+F1W/Ka6o8fjaeYvjPcP7U6uaZJW4FFY4Ll6+lGYH0NtAxmRt0A==,iv:tHpoHLeGS+cH3Wjc9K4RgTnQ4t0zs0CNt6Yaql7Lo6I=,tag:HWaznKP/26TDKlU5cTSvHQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:F94ew7KXvHrAUYXe34AmyyrO/WTu818ItVD9ExFovAjvzTiOXa1kwDkHiRYIM4IMFxmRojMdshUEltu1w7OICU3crdUCMY0KP7fVTlxn9wa2a36YqQY2uDT0b2Ff1O65Q3ouno4F7N533aWN6aCGiSSBqtgQiNfFwH+lJ/376t7wJQi4KpH4FKX6v0K2dhs681hIReYH39FzwtVXwjeDgB9UQT5/Ph2mVgdQ/RbOIo5OMqFK/UT5bgN6jRA3AbQcsd2LpJ+VoQJzp8LNXA==,iv:2FNF3LzpgWnyPz/xnrS1488vSetlxT0+hk8SUuG4K+A=,tag:FQUO0AwGB1xek5nnyZA6xA==,type:str]
    known_hosts: ENC[AES256_GCM,data:MjLxAgreALR5s0EM4ZW3Y73thskGYvage87i9Zpoho6R3z0Yfw3gIcXqK4tB6NX34cxmmMkAZMuVX3eYlCYdPWyesiKRL0Wzb/AbMh/dYvbyo0El4UP9FacrkI05tgkngVn/xBVvgPWndxWSSDZw5x+bpPJryWhars3QuCNKx3ryo7YCLOxMDRjHLJSJErXEwiU8+L2zQ+sCYDgkNAtOFAr4NdzesAUbjma/,iv:CrYYIAjLbKDCuCgNhhS949Wk1fJii1ozR2quA80QBv8=,tag:zZBzwcSFlbvN4bzDhlpycg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXZQZlFsVWJBT3RYVVgy
            NW10eWd2VFhzSjdadEFxWUo2bmR4enhzb200CnpGOStmLzBPUzJFK2NKYlJGcjZH
            WDN1YUx4VksyUVphdEVWRFIzWWs4VkEKLS0tIGhWWUlXbVZUbHd4RVdUSDVFNjJ3
            ZVJ2MFRtY2NCSjBJV3ZzbVNUV01LSkEKp9f8fkZOP91PzCayLxq+/ya/PKC39xl0
            5KFWEv0duowSx8lQ3zJht7wtWsotx+vVUkZMByf67PGmJx/Zlr87Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-17T21:30:47Z"
    mac: ENC[AES256_GCM,data:b/95Q5rp2onMyEorRKhDAIFx5mAuB0spsyE4R9enazQwX92PUF66EU3qC+gwQijtl5tBQ+XmUKXpedrXsFE1jFaGKwjC4pUHwhmZpCUKbqDSsg3kHLCgg/AjNsYoviBAuJ6I62/gaIDdo6W8IWp0fFYYd7q4BB7VTkm89S4yRUA=,iv:oDHSpP9akO4iUHHbuyTqZ1PnKzVMkCVf7zXs9jHvJ9k=,tag:aJXCP7jK20ME9KwA5lFt9w==,type:str]
    shamir_threshold: 3
    version: 3.13.1
