apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BrkMX4OPzgHRY8URfx4aPhyE/2Ed4hhd6fDHEabPW+AUsnT9KhIejGVkRx8B+IMMWqDjYG75kjQE2Nq8vKJnsWkb4dctOZgvvbFpa0RCoTxb3Pb+RjTObBWgYRvlcDuHcjfDwdXP+HzC4Ywm0hZa9njMQZrrJHHP3ZVFaOV01/RWVFLx16v5Cu1N9pBysNaP5NEK7G+038951gcDVNmZfuRKiaLwePS/oWPpNQsQeYSk+QDC8e3aNA4j21LbbfSyPGt2mBU2RR8oQjpX+Qya8z6v+XnDuw2PwD8aqjL7JBVxlbFYmnDaj2/jLcU45X8PFTyzeOgN84XYyV+lIk0iuBmtVvADvLZ/YhWiKjl6n9THH4B/7BHiK6zqw/yt5Q68,iv:oiXS5XM+kuqFQrHpBEE3f6xEkIzTIihq0I61YS6ohEY=,tag:lBghxPhPQhSGwPKUDsFCjQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:HRnrZ4gkifuihw5PmnHFXExhnpjWDJkEaqV15dGVObytCxs/FCSrcbbqBDuJFIqcA7Imk+6Ta3+fUsv3Wgsz1G+Hqw1oyD2D+5vbByGvuWWqe3ysv1tUnOmSApvkQO8UxO8EF50jffjC1vF4sZ5a5uAIThanbyZAU/T7Gh0V13S0OSzrYmCCgSi/auuADD5iw3N9L/WEh8cWlhzFcfJw0GPusxBwBh/RP4yIeUwHVt2/7XJJkH0RTKwRoopmL76YAYc0/pH51jxQ2UHyeg==,iv:rFqW8tm+RaAG6JweNcaY/jeaFMy1ylbgSelS0LTU9PM=,tag:9It0nLiFxJVkfa/4200TLg==,type:str]
    known_hosts: ENC[AES256_GCM,data:y/T6qjCagpFmwErHVgZr7KzFH1YsQ9JBJEg2oAJyFDS9njPOqU6CXG8VXWsMOikm7BG6GyptCEdTTh6Zu3ihCYq8kk8vAAzihwu6H7H21/A0s/GPwhAaUPRzgjAXEJ6MnPA1+hqvF267KRS8O9Q+CRyfBCJ7UWJ2jgJJh0sNUBCSnUFUSLG1fEXvlsuUvgAgx7fGcERTZPfoXH3O8uHYXv9qabiS6JeAx0Yf,iv:Y5podpf7VM3BMGW9g2mRV4qsHMYTMHbdg20jLxC4qp0=,tag:56HVGN2OmDo+9CYBa9zSJQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVndrbzUyU0hQelR1UXpF
            cDhBbXo3TzU1VHVIZ3JCdGZ3R1RSdkdtTVNZCmp6UkdNK25BKzNFWkVRa0hjYU90
            Ykc1bDlkaEdTSjlCeWg2TDhkdmc3d1kKLS0tIGsyWFBySlJsY0Y4TU9HSDdFeVRD
            ZkQwRkd4QStSNitPOEJuZ2Zwa0tSQ0EKgOtWEfBt0TPt+UEozWw6QXGN/oOEE9S9
            QpT4s0YwBAZghjb/6exS5L6HJJfiElsU/ToYm29q/MmizmXMC0BRhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-11T17:22:00Z"
    mac: ENC[AES256_GCM,data:1kD8Xpj4LzKZR3rDrXqQV+lkmQ1yuaGBB3CfH6W2SZQ3AsUdYSNp8VKxsLDvZYE+ZLZNvvd+K+Ifptd+w3+4sMQJ6fRADwBEGPs8P2Fc7La6keqf/852VaMyN0t5PwvKyhX4Ma8iF/JMwGX58FnkQDBmgCtpjAfpFLEDWrbHm/E=,iv:bRNMpoHo5GudmGB76gZWuWEkwvoKGkNcu68WraF+Taw=,tag:6aU0uBQn2PT+0fT5FM871A==,type:str]
    shamir_threshold: 3
    version: 3.13.1
