apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fjsraac4aeFtqa9aJpE7iutpEOF0qbtBHFvOMNwlE9urVN70TYtGr0UbT2oYwWowbvwxNPJvNYU3RuMBA4RlvzGiaYSnWZdBhdriL/0qJieEwgxba21GPxqvsGYNv7vkSt426SLwv8KZkx1/CfqqsLd2ao3U9tgUKANzM3EowR1S3jcqMfy4O3LmXOHpOgyoNsxXZKhMqgo1DRT6dx9nl0/JEsNd1WzOAvz0X2pdLSNDG1UnRpK3gI44Uzcg86klhc63s/O8sZyuKVR163JRVWg211y0Lv7EIa86DOxB1qdkmvA9UeNwGpRTnI/TnXnzI4Y4RXWp8YAJGvw1yKMMAssYjpmIWIZ8VcQK971aZINItZGmxvuKeo4ChGh33xdLmLMW4URyA2JaAwg+PlIdVT4G/MOmbPHmraABQ7TNSM9SOpzo4eQIMlD0iaaVTDZv7p2YKkhGWjoIbWXiBvhCyHoGMY+0TvPeEoy1jgcNDsSFZJUOniK9LTwbRPwbFYkXbdaasilgANSut4GG6elDrMW9I+tzpJN9cznhquxYot6pKT5nE0P7+OYhs/Rww5eRbD6comqghMJjikl0grPPolZtzVbCYJVm8Cd9VZECRI0NcyWstlwT9xsALf929sAf9IepWEj1qwEx/81kkjPDeC4roAbh/t1572o2O9swyfEsf6U3KeT4O2p0kre8f36CPr1tr2b7uK9Nu6dkehOePFbV4FBH+VHk1xi/jEOf664VcA95TEqNhmIbW+KA0v/ykd0SqTweYlEhl5gIhIz7zHBue6qiuYTD5Is0qnrVK8o9EgmqEWMb1IT0pfqf4Q==,iv:lChdW+wHgRJQI/lEa7A0UwNNmC03waQNNJ8rmU79i/8=,tag:x52tmlhr653oHiMhdKl9rg==,type:str]
    identity.pub: ENC[AES256_GCM,data:slcgW/OLLDg9gDXDKsA6UiunmkEMerBbY3l2CLq9VTTN32bkG1jnuuwqcNIhOqNI9dHYkf34WHxDGBFsVo3yF/JKtlDhW45GWzCJpa9BMxI/8ZBeVeTPr1ExBZZAoJDkjJN282qcqINP5olgO+6JuAQnR2NzqJQp2XY4zoZzbGo3SzzvIBSYwY04PtWagks9BpM3ckya3UwtebHpjr6mbgud6MuinVrPlcD8No090WYwc4iZu00KvmPmtolQCDNNXRFV1HihYjj+PZQ8Xg==,iv:0H74K1psGy8qFhCPXqKMxJk9Gv2uWQtrJkm8TeEA30o=,tag:5UaqtolKK+p2Ozzrf6VJKQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:J0HFPT0HwkUJxYOcwH0++gLT+YRpnxJLLOTIk4bRUUcvKJt8W/qufchdvWvezqxpi4u2ipHibxhWAMx7khY0rPhUfaIaeIiRgnD4eiCXihSRC05Av+zQuWg/Q4TQGkffVJkPnYSOTRXcTX7oBpMK2FrCMC/TEWa8ZAhyhb0UV7XT6AlK1pYvxKF2fivbBKMno69/qsO01iPW/59IuX1RrDOUtwmCg545Eapk,iv:dhvI2VS6s8YYcT6o6i2+1roMrTSkLwhTc+tgQkSFkp4=,tag:eQdGJGDHvxnMod2OT1STsA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMm9iUUZ5RUhkOGN2V0c4
            QS9ZbFBjVTQrTVRFc2N5WWs0ajBxUXZ2YTE4CnE0QjUwOUZ5VGZCV1U1RDVSK21u
            Y2QwbVlmUWw1M2tnY3lOTlNnY1VmazAKLS0tIEswQzJQUkdsalFpb1VqdkhqOERI
            SG9DcmI2MjNpZGw4SXBINURENERSMFUKw21NMOcOHZB3FSmtRJitvRjfpTabw/Cu
            qHYJgCQEqo2gjDi7k7plWTCfKTSz0BkiG5tB93MMxN0OdoS8ObuCZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-17T09:25:58Z"
    mac: ENC[AES256_GCM,data:WB/2iDZJo1MjFvHn7U2AAbT4PAo1pIaoRp+ghJEHG3Ptwx/FQCWV2TbPQ62mV1d+yeD+xSITHBFOqc8Q/d8F+AnssWqinB2wog1gZ5UQBPoc1mhh8ByOahOmyG4QZc2q3CeeKuabqi30ziFZQhbOJCX85xlJ2KZqBGHV5gBEeKg=,iv:cImYgHL46MV5U9b0DynK6yOIfuxGj4USREMLdzG7s9c=,tag:DvcrGYpduNlNfXEZ9nq0pw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
