apiVersion: v1
kind: Secret
metadata:
    name: deploy-key-oreste-charts
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wuYC6YDrbBzwjJU4qED9qm2jL01sf5VbI9Iwums02YAb//g0vxh+quxQUs0IJSTJfbh1ZGI0uFdTRAw8AtaXl7QEeY0Fh1rZ5+lEAo3xc6fiv6pIa5ubB7odSV24ZW6VJlVaHbdXSO6T7oIg89sfua2PKabxlRtotmNR0OCqPnE7bBJpnMrHgAY0RnoqK7YQW4tb5iIF1/BZusCwr9lGRTLJvI38j2jZeM3RuypneOMOp36LARf58WJyTXaxX+KLLIj9Zz1+t+tm4qXFfbdR3SqBG8jOtIhe86bDXQkhrzUjTjvhvSN13Ibgv7v42cdQAJb85Bj+wpQECIGUPkKm9SCndOwiIu59rbIoFclPrVrGXfKS0Un4KtED7tTiyABBC8sY4pgPURUqMvTlpKQYtBRHiViJPSU7Ny6kyhqxUlga3OE9aNeYXlzxEKo48MVYFOWR7cG+KoWqtWcNjrS35EDGOBbwFdvFpaXOQJDmLR9Mq/nZEvW0dSEtTnPqG6wQvt4xxC8+hOEAsU6FAJw9eDGnzoSkJ+SrcJCNAb8J/35q1q66vIeOohybTGX74HtMV10eflT0BMg81Uh2cIn2AhiQGwQmzQYjhrfpNvujTTIcMIxdDuxDUEVF1CAPbHjamh4T9EcZ+3Vhnoe7dHcwQsuPpArRoFgV8OiYnvXBPYBDJx2DdEsufZkboKk9pKXT4c/F/HXbxQU4ANgpIEGklPELo0ZY1iavGdmvSQYwuRuFev/hfsLMZ4LRa44E+QnBPNvFmLWq8b3LkSNYzsc7iVPUWJjjD/DU5N0V3b9rhZh4RCDFKlLyT6EG/9jneA==,iv:6XZ7WOJzYUFLw78QA1ipgl8uLUJyz0skyRp+gmWjcrw=,tag:PoCP37cLjSE3Zhn++f1F2g==,type:str]
    identity.pub: ENC[AES256_GCM,data:c2sOlGRUC/QvceVk+IUreOCJX6kV3o6lLS4uwF2n0WorOPfpzlZ17FD3LxuH0Uh9Aok4jlvlRajOG2ubp9tvCj92QHBH0PGXQozs+lPKoVg3CM6M9y7x9eCHXR9GswxBQ7pq1LlBP6TtiAgQgo4e7IxzAOdfVGTle4KVOcnzhYkHk3plcfP71Lij0IrTRso2mBTFfDYp/rnB+86TNNmOR+cwya/GzWHOuAgNbDZqMIm7HE+FzyhuAQQBW9eU4T2fx2Zv1vdyAyRFrLitLw==,iv:sDht0TfCdMWZxBhRuTP+4vTJWJabAlsXgRuSU2V6IXo=,tag:wHoAU10+ds50r3AaqlGodw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BP7TaPAGsn7l0Bq5gza36uytdEzrLRp9O7n8BM3ntYOBbn6rgxV/Qs/E8HfUV7m1n6t1pqptL52X5vapTKNA4d9SK6Fz4eB1wcX2mUrJysDMnOj3WMnuotfJqWVLQ5seSInEb9g52cHlhJzw+ratgo65IBDP4VJmhGS99i4kkNg2F1Vj3p+l9QrBwgHfrp6HRAM+9dUHAtZ7AoPGEhMNpGLmLMiTsrYuxwdP,iv:TUAiv6ixNl/02EXYhZ5yAASdBKnbd/1I8hMTc8HSPGQ=,tag:IuS2URm6oje2zxnmUH/MHQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnKzFmOVhadzNwVHc0bGxK
            NmFPODV1WUxuZ1N1dmdFUExFQkE5L2x1dzNZCnRWUFdjellnWlZhNFIrMTBmVmlP
            RitoRnMvVG05NStWSmFQUXV2ZTh6ZW8KLS0tIE53OEYzdXFLdU04RVFhTU91TmZj
            Q21YOUFva2xqZVRMT09SOVRTR1RHeDgKqsri4XkaSSiNKQgxyYzgxAdr6rtRqV9P
            qZxVhsFCwvo+8Xi0HvULZdRZpf1h+Xm+dXxna4ITK3RuXpMfM5UNeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdddrfl5cj8z0xsguyyg64a90s80v823uaee7afdnadxl4ml5tsznljr7
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-06-09T17:55:15Z"
    mac: ENC[AES256_GCM,data:a2DjkEvymVDUzsR8CTge1KbBrDU8bYvvfv6ecGesD6Xt/LljIh8NPs0Kis9VlPYoGhTzbn2DNK594xVXI9zQErML+lk40+zjZcvAFt3DkNK9ITtO4XeHYkb0J0JO5xwgodgwqRHcQjzVDFSaXBJ7ldpuc0vRDmPSP+tOquGdOzA=,iv:p9fcE4/uUrzoLe6wmFl/93WsD0c6CXWrx1Q8ScmhQwk=,tag:p7I2S9GrRc9N7DIspiR9LA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
