---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 15m
  chart:
    spec:
      chart: frigate
      version: 17.0.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    frigateConfig:
      mqtt:
        enabled: False
      cameras:
        magazzino:
          enabled: True
          ffmpeg:
            inputs:
              - path: "rtsp://${CAMERA_MAGAZZINO_USR}:${CAMERA_MAGAZZINO_PSWD}@${CAMERA_MAGAZZINO_IP}/streaming/channels/101"
                roles:
                  - record
              - path: "rtsp://${CAMERA_MAGAZZINO_USR}:${CAMERA_MAGAZZINO_PSWD}@${CAMERA_MAGAZZINO_IP}/streaming/channels/102"
                roles:
                  - detect
          detect:
            width: 640
            height: 360
          onvif:
            host: "${CAMERA_MAGAZZINO_IP}"
            port: 8000
            user: "${CAMERA_MAGAZZINO_USR_ONVIF}"
            password: "${CAMERA_MAGAZZINO_PSWD_ONVIF}"
        ufficio:
          enabled: True
          ffmpeg:
            inputs:
              - path: "rtsp://${CAMERA_UFFICIO_USR}:${CAMERA_UFFICIO_PSWD}@${CAMERA_UFFICIO_IP}/streaming/channels/101"
                roles:
                  - record
              - path: "rtsp://${CAMERA_UFFICIO_USR}:${CAMERA_UFFICIO_PSWD}@${CAMERA_UFFICIO_IP}/streaming/channels/102"
                roles:
                  - detect
          detect:
            width: 640
            height: 360
          onvif:
            host: "${CAMERA_UFFICIO_IP}"
            port: 8000
            user: "${CAMERA_UFFICIO_USR_ONVIF}"
            password: "${CAMERA_UFFICIO_PSWD_ONVIF}"
        citofono:
          enabled: True
          ffmpeg:
            inputs:
              - path: "rtsp://${CAMERA_CITOFONO_USR}:${CAMERA_CITOFONO_PSWD}@${CAMERA_CITOFONO_IP}/streaming/channels/101"
                roles:
                  - record
              - path: "rtsp://${CAMERA_CITOFONO_USR}:${CAMERA_CITOFONO_PSWD}@${CAMERA_CITOFONO_IP}/streaming/channels/102"
                roles:
                  - detect
      record:
        enabled: true
        retain:
          days: 7
          mode: motion
      birdseye:
        enabled: True
        mode: continuous
      camera_groups:
        AI_Vallecrosia:
          order: 1
          icon: LuApple
          cameras: ufficio

    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_KEY}"
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.10.66
      
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: frigate.cloud.local
            paths:
              - path: /
        tls:
          - hosts:
              - frigate.cloud.local
        integrations:
          traefik:
            enabled: false
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
             enabled: true
            src:
              enabled: true
      media:
        enabled: true
        type: nfs 
        mountPath: /media
        path: /mnt/DVR/Frigate-Recordings
        server: "10.0.10.10"