---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: omada-controller

spec:
  interval: 15m
  chart:
    spec:
      chart: omada-controller
      version: 17.11.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_KEY}"
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
             enabled: true
            src:
              enabled: true
      work:
        volsync:
          - name: work
            type: restic
            credentials: s3
            dest:
             enabled: true
            src:
              enabled: true
    service:
      main:
        ports:
          main:
            port: 443
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: internal
        hosts:
          - host: omada-controller.cloud.local
            paths:
              - path: /
        integrations:
          traefik:
            enabled: false
