apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress-guests
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/wordpress-guests/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

