apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release-don.yaml
  - helm-release-casaebottega.yaml
  - mariadb_backup_casaebottega.yaml
  - mariadb_backup_don.yaml
